"""Public module contracts for Media Finder extensions."""

from .common import PublicModel
from .conformance import (
    DownloadClientConformanceFixture,
    MetadataConformanceFixture,
    ReleaseConformanceFixture,
    assert_download_registration_conforms,
    assert_metadata_registration_conforms,
    assert_release_registration_conforms,
)
from .environment import ResolvedModuleEnvironment, resolve_module_environment
from .errors import JsonScalar, JsonValue, ModuleError, ModuleErrorData, ModuleFailureCategory
from .manifest import (
    AttributionSpec,
    EnvironmentVariableSpec,
    ModuleKind,
    ModuleManifest,
    load_manifest,
    parse_manifest,
)
from .protocols import DownloadClient, MetadataProvider, MetadataRetentionPolicy, ReleaseProvider
from .registration import (
    SDK_VERSION,
    SUPPORTED_CONTRACT_VERSION,
    DownloadClientRegistration,
    MetadataProviderRegistration,
    ReleaseProviderRegistration,
    StaticModuleRegistry,
)
from .schema import generate_schema_artifacts, write_schema_artifacts
from .types import (
    Artwork,
    CorrelationResult,
    DownloadArtifact,
    DownloadDestination,
    Episode,
    ExportHeader,
    ExportWarning,
    MagnetArtifact,
    MediaKind,
    MetadataIdentity,
    MetadataSearchQuery,
    MetadataSearchResult,
    NormalizedMetadata,
    Person,
    PrivateReleaseSelection,
    Provenance,
    ProviderPayload,
    Rating,
    ReleaseCandidate,
    ReleaseSearchFilter,
    ReleaseSearchQuery,
    RetentionAction,
    RetentionActionKind,
    RetentionPolicy,
    RetentionSubject,
    SafeReleaseSnapshot,
    Season,
    SubmissionResult,
    TorrentArtifact,
)

__all__ = [
    "SDK_VERSION",
    "SUPPORTED_CONTRACT_VERSION",
    "Artwork",
    "AttributionSpec",
    "CorrelationResult",
    "DownloadArtifact",
    "DownloadClient",
    "DownloadClientConformanceFixture",
    "DownloadClientRegistration",
    "DownloadDestination",
    "EnvironmentVariableSpec",
    "Episode",
    "ExportHeader",
    "ExportWarning",
    "JsonScalar",
    "JsonValue",
    "MagnetArtifact",
    "MediaKind",
    "MetadataConformanceFixture",
    "MetadataIdentity",
    "MetadataProvider",
    "MetadataProviderRegistration",
    "MetadataRetentionPolicy",
    "MetadataSearchQuery",
    "MetadataSearchResult",
    "ModuleError",
    "ModuleErrorData",
    "ModuleFailureCategory",
    "ModuleKind",
    "ModuleManifest",
    "NormalizedMetadata",
    "Person",
    "PrivateReleaseSelection",
    "Provenance",
    "ProviderPayload",
    "PublicModel",
    "Rating",
    "ReleaseCandidate",
    "ReleaseConformanceFixture",
    "ReleaseProvider",
    "ReleaseProviderRegistration",
    "ReleaseSearchFilter",
    "ReleaseSearchQuery",
    "ResolvedModuleEnvironment",
    "RetentionAction",
    "RetentionActionKind",
    "RetentionPolicy",
    "RetentionSubject",
    "SafeReleaseSnapshot",
    "Season",
    "StaticModuleRegistry",
    "SubmissionResult",
    "TorrentArtifact",
    "assert_download_registration_conforms",
    "assert_metadata_registration_conforms",
    "assert_release_registration_conforms",
    "generate_schema_artifacts",
    "load_manifest",
    "parse_manifest",
    "resolve_module_environment",
    "write_schema_artifacts",
]
